[project]
name = "mig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zhifan Li", email = "z2367li@uwaterloo.ca" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "utils",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "utils",
    "qa",
]

[tool.uv.sources]
utils = { workspace = true }
