[project]
name = "utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zhifan Li", email = "z2367li@uwaterloo.ca" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
core = "utils:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
